; Devilx default config (ASCII for Windows ConfigParser)
[Smtp]
Email = none@local
Password = none
Destination = none@local
Server = localhost
Port = 587

[Settings]
Password = none
Api_Key = None
Proxy_List = Proxies/Proxy_list.txt
Show_Logs = False
